# Generated by Django 6.0.5 on 2026-06-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
